/**
Tehtävä 1 - Eurot markoiksi ja päinvastoin (Kotitehtävä)
------------------------

Tee ohjelma, jolla voidaan muuttaa euroja markoiksi ja päinvastoin.
- sovelluksessa tulee olla graafinen käyttöliittymä (voit ohjelmoida itse tai 
käyttää apuna NetBeansin GUI-editoria)

Vihjeitä:

// Käytä JLabel, JButton ja JTextField-komponentteja
// Tekstin voit lukea JTextField-komponentistä esim. String muuttujaan seuraavasti:
String raha = markkaText.getText();
// uuden lasketun raha-arvon voit sijoittaa JTextField-komponenttiin esim. seuraavasti:
euroText.setText(arvo);

Tekijä: Mikko Pakkanen
Pvm: 03.03.2015
**/

package fi.jamk;

public class ValuuttaMuunnin extends javax.swing.JFrame {
    
    public ValuuttaMuunnin() {
        super("Valuuttamuunnin");
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textEuro = new javax.swing.JTextField();
        textMarkka = new javax.swing.JTextField();
        buttonMuunna = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEuroActionPerformed(evt);
            }
        });

        textMarkka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMarkkaActionPerformed(evt);
            }
        });

        buttonMuunna.setText("Muunna");
        buttonMuunna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMuunnaActionPerformed(evt);
            }
        });

        jLabel1.setText("Euro");

        jLabel2.setText("Markka");
        jLabel2.setToolTipText("");

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textMarkka, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonMuunna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonReset))
                    .addComponent(textEuro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMarkka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMuunna)
                    .addComponent(buttonReset))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEuroActionPerformed

    private void textMarkkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMarkkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMarkkaActionPerformed

    private void buttonMuunnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMuunnaActionPerformed
        String eurot, markat;
        double kurssi = 5.94573;
        
        // Jos jompikumpi kentistä sisältää jotakin
        if(!textEuro.getText().isEmpty() || !textMarkka.getText().isEmpty()) {
            markat = textMarkka.getText();
            eurot = textEuro.getText();
            double luku_markat = 0, luku_eurot = 0;
            
            // Muunnetaan euroiksi jos markat-kenttä ei ole tyhjä ja eurot on
            if(!textMarkka.getText().isEmpty() && textEuro.getText().isEmpty()) {
                // Yritetään muuntaa käyttäjän syöte liukuluvuksi
                try {
                    luku_markat = Double.parseDouble(markat);
                    luku_eurot = luku_markat / kurssi;
                    eurot = ""+luku_eurot+"";
                    textEuro.setText(eurot);
                    //System.out.println(luku_eurot);
                } catch (NumberFormatException e) {
                    System.out.println("Syötä arvot lukuina");
                }
              // Jos taas eurot-kenttä ei ole tyhjä ja markat on
            } else if (!textEuro.getText().isEmpty() && textMarkka.getText().isEmpty()) {
                try {
                    luku_eurot = Double.parseDouble(eurot);
                    luku_markat = luku_eurot * kurssi;
                    markat = ""+luku_markat+"";
                    textMarkka.setText(markat);
                } catch (NumberFormatException e) {
                    System.out.println("Syötä arvot lukuina");
                }
            }
        }   
    }//GEN-LAST:event_buttonMuunnaActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        textEuro.setText("");
        textMarkka.setText("");
    }//GEN-LAST:event_buttonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValuuttaMuunnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValuuttaMuunnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValuuttaMuunnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValuuttaMuunnin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValuuttaMuunnin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMuunna;
    private javax.swing.JButton buttonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textEuro;
    private javax.swing.JTextField textMarkka;
    // End of variables declaration//GEN-END:variables
}
